#!/usr/bin/env bash
# CustomPiOS module : docker
# Original script written by Damien DALY (https://github.com/MaitreDede/)
# Changes by Guy Sheffer
# GPL V3
########
# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -ex

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


apt-get update
apt-get install -y docker.io


if [ "${DOCKER_ADD_USER_TO_GROUP}" == "yes" ]; then
    usermod "${BASE_USER}" -aG docker
fi

if [ "${DOCKER_COMPOSE}" == "yes" ]; then
    apt-get install -y python3 python3-distutils python3-dev python3-testresources gcc libffi-dev build-essential libssl-dev cargo python3-cryptography python3-bcrypt
    # Docker-compose
    wget https://bootstrap.pypa.io/get-pip.py -O - | python3
    pip3 install --ignore-installed PyYAML
    pip3 install docker-compose
fi


if [ "${DOCKER_COMPOSE_BOOT}" == "yes" ]; then
    unpack /filesystem/root /
    unpack /filesystem/boot /"${BASE_BOOT_MOUNT_PATH}"
    
    if [ "${DOCKER_COMPOSE_BOOT_PATH}" == "default" ]; then
        DOCKER_COMPOSE_BOOT_PATH_ACTUAL="/${BASE_BOOT_MOUNT_PATH}"/docker-compose
    else
        DOCKER_COMPOSE_BOOT_PATH_ACTUAL="${DOCKER_COMPOSE_BOOT_PATH}"
    fi
    sed -i "s@DOCKER_COMPOSE_BOOT_PATH_PLACEHOLDER@${DOCKER_COMPOSE_BOOT_PATH_ACTUAL}@g" /etc/systemd/system/docker-compose.service
    sed -i "s@DOCKER_COMPOSE_BOOT_PATH_PLACEHOLDER@${DOCKER_COMPOSE_BOOT_PATH_ACTUAL}@g" /usr/bin/start_docker_compose
    sed -i "s@DOCKER_COMPOSE_BOOT_PATH_PLACEHOLDER@${DOCKER_COMPOSE_BOOT_PATH_ACTUAL}@g" /usr/bin/stop_docker_compose
    systemctl enable docker-compose.service
fi

#cleanup
apt-get clean
apt-get autoremove -y
