#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}


#echo_green "Move script..."
#unpack /filesystem/home/pi/
#echo_green "Move script...(DONE)"
echo_green "Unpack file..."
echo_green "Script Home Assistant..."
unpack /filesystem/home/pi/install-HomeAssistant.sh /home/pi/install-HomeAssistant.sh pi
echo_green "Unpack file...(DONE)"

echo_green "Install Docker Home Assistant..."
sudo chmode /home/pi/install-HomeAssistant.sh
cd /home/pi/
sudo chmod +x install-HomeAssistant.sh
sudo ./install-HomeAssistant.sh
echo_green "Install Docker Home Assistant...(DONE)"
