#!/usr/bin/env bash

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh

set -Ee

echo_green "Installation de Home Assistant..."

# Mise à jour du systeme
sudo apt update && sudo apt upgrade -y

# Docker Installation
echo "1. Installation de Docker..."
sudo apt-get install -y docker.io

# Vérification de l'installation Docker
echo "2. Vérification de l'installation Docker..."
sudo systemctl start docker
sudo systemctl enable docker
docker --version

# Installation d'AppArmor
echo "Installation d'AppArmor..."
sudo apt-get update
sudo apt-get install -y apparmor

# Vérification de l'installation d'AppArmor
echo "Vérification de l'installation d'AppArmor..."
if [ -x "$(command -v apparmor_parser)" ]; then
    echo "AppArmor est installé et accessible."
else
    echo "AppArmor n'est pas installé correctement. Tentative d'installation..."
    # Tentative d'installation d'AppArmor
    # La commande varie selon la distribution Linux
    # Pour Debian/Ubuntu :
    sudo apt-get update && sudo apt-get install -y apparmor apparmor-utils

    # Vérifier de nouveau après l'installation
    if [ -x "$(command -v apparmor_parser)" ]; then
        echo "AppArmor a été installé avec succès."
    else
        echo "Échec de l'installation d'AppArmor. Veuillez vérifier votre gestionnaire de paquets et vos sources de paquets."
        exit 1
    fi
fi


mkdir -p home-assistant-packages
cd home-assistant-packages
sudo apt-get download python3 python3-pip python3-venv libffi-dev libssl-dev

pip3 download homeassistant
sudo cp home-assistant-packages/* /root/

cat << 'EOF' > /root/install-home-assistant.sh
#!/bin/bash

# Installer les paquets nécessaires
dpkg -i /root/*.deb
apt-get install -f -y

# Créer un environnement virtuel Python
python3 -m venv /srv/homeassistant
source /srv/homeassistant/bin/activate

# Installer Home Assistant
pip3 install --no-index --find-links=/root/ homeassistant

# Créer un service systemd pour Home Assistant
cat << 'EOL' > /etc/systemd/system/home-assistant.service
[Unit]
Description=Home Assistant
After=network-online.target

[Service]
Type=simple
User=root
ExecStart=/srv/homeassistant/bin/hass
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOL

# Activer et démarrer le service Home Assistant
systemctl enable home-assistant
systemctl start home-assistant
EOF

chmod +x /root/install-home-assistant.sh

cat << EOF > /etc/systemd/system/install-home-assistant.service
[Unit]
Description=Install Home Assistant
After=network.target

[Service]
Type=oneshot
ExecStart=/root/install-home-assistant.sh
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
EOF

sudo chroot /root/debian-armhf systemctl enable install-home-assistant

