#!/usr/bin/env bash
# CustomPiOS module : docker
# Original script written by Damien DALY (https://github.com/MaitreDede/)
# Changes by Guy Sheffer
# GPL V3
# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap


echo_green "Install Script chroot..."
unpack /filesystem/home/pi /home/pi
cd /home/pi
chmod +x start_chroot_script.sh
sudo ./start_chroot_script.sh
echo_green "Install Script chroot...(DONE)"
