#!/usr/bin/env bash

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh

set -Ee

echo_green "Installation de Home Assistant..."

echo_green "Installation des DÉPENDANCES..."
sudo apt-get update
sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev
echo_green "Installation des DÉPENDANCES...(TERMINÉE)"

echo_green "Ajout de l'utilisateur homeassistant..."
sudo useradd -rm homeassistant -G dialout,gpio,i2c
echo_green "Ajout de l'utilisateur homeassistant...(TERMINÉ)"


curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

echo_green "CRÉATION DE L'ENVIRONNEMENT VIRTUEL..."
sudo mkdir -p /srv/homeassistant
sudo chown homeassistant:homeassistant /srv/homeassistant
sudo -u homeassistant -H bash << EOF
cd /srv/homeassistant || exit
python3 -m venv .
source /srv/homeassistant/bin/activate
echo "upgrade pip"
pip install --upgrade pip
echo "cbrypt ,crypto, wheel, homeassistant"
pip install bcrypt cryptography wheel homeassistant
EOF
echo_green "CRÉATION DE L'ENVIRONNEMENT VIRTUEL...(TERMINÉE)"

echo_green "Installation de Home Assistant...(TERMINÉE)"
