#!/usr/bin/env bash

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh

set -Ee

echo_green "Installation de Home Assistant..."

echo_green "Installation des DÉPENDANCES..."
sudo apt-get update
apt install apparmor bluez cifs-utils curl dbus jq libglib2.0-bin lsb-release network-manager nfs-common systemd-journal-remote systemd-resolved udisks2 wget -y
echo_green "Installation des DÉPENDANCES...(TERMINÉE)"

echo_green "Install Docker-CE..."
curl -fsSL get.docker.com | sh
echo_green "Install Docker-CE...(DONE)"

echo_green "Install OS AGENT..."
wget https://github.com/home-assistant/os-agent/releases/download/1.6.0/os-agent_1.6.0_linux_armv7.deb
sudo dpkg -i os-agent_1.6.0_linux_armv7.deb
echo_green "Install OS AGENT...(DONE)"

echo_green "Install Home Assistant..."
wget -O homeassistant-supervised.deb https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
apt install ./homeassistant-supervised.deb -m qemuarm
echo_green "Install Home Assistant...(DONE)"

echo_green "Installation de Home Assistant...(TERMINÉE)"
